# Generated by Django 3.2.4 on 2021-06-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0002_customer_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tracking_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
