# Generated by Django 3.2.4 on 2021-06-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0005_alter_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('Shipment - Delivered', 'Shipment - Delivered'), ('Shipment - Pending', 'Shipment - Pending'), ('Shipment - Cancel', 'Shipment - Cancel'), ('Shipment - Complete', 'Shipment - Complete'), ('Shipment - Return', 'Shipment - Return')], max_length=200, null=True),
        ),
    ]
